version: "3.8"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes: #변경사항을 docker image에 실시간 반영하게 해 준다?
      - ./frontend/:/frontend
      - ./frontend/node_modules:/frontend/node_modules
    command: >
      sh -c "expo start -c"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS= 0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.1
      - EXPO_DEBUG=true
    stdin_open: true
    tty: true
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ./backend:/backend
      - ./backend/account:/backend/account
      - ./backend/challenges:/backend/challenges
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=Dustar
      - DB_USER=postgres
      - DB_PASS=star
    depends_on:
      - db

  db:
    image: postgres:9.6.24
    environment:
      - POSTGRES_DB=Dustar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=star


#Dockerfile은 도커 이미지를 만듦.
#가져올 거면, 굳이? 