# Generated by Django 3.2.9 on 2021-11-20 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('dust_type', models.CharField(blank=True, choices=[('ambitious', '야망있는 먼지'), ('popping', '통통튀는 먼지'), ('tiny', '조구만 먼지'), ('exciting', '신나는 먼지')], max_length=10, null=True)),
                ('big_star', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('small_star', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
