# Generated by Django 3.2.9 on 2021-11-20 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('max_people', models.PositiveIntegerField(default=0)),
                ('period', models.CharField(choices=[('OW', '1주'), ('TW', '2주'), ('THW', '3주'), ('FW', '4주')], max_length=3)),
                ('big_star', models.PositiveIntegerField(default=0)),
                ('small_star', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('is_full', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
